### PR TITLE
Add fall 2014 talks

### PR DESCRIPTION
**Pull request by ajm188**

### CODE REVIEW

**Comment by thomasrussellmurphy** [comment]
Looks good to merge and deploy to the `gh-pages` branch.

**Comment by ajm188** [comment]
Getting an exception while running the deploy script.

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 24: ordinal not in range(128)`
Investigating.

**Comment by ajm188** [comment]
```
git checkout master~1
python generate_html.py
```
Same error.

**Comment by thomasrussellmurphy** [comment]
Someone dun Unicode somewhere?

**Comment by ajm188** [comment]
Works if I use `python3.4`. Deploying and making an issue.

**Comment by thomasrussellmurphy** [comment]
Ah, lovely.

**Pull request merged**
